### ISSUE TITLE
list "mkdocs" in requirements.txt

### ISSUE THREAD

**Issue by soxofaan** [EOEPCA/document-template#1]
https://github.com/EOEPCA/document-template/blob/6bc682385d684e189e28fcbba1e4d297edfc0a0f/docs/requirements.txt#L1-L3

shouldn't this (at least) list mkdocs as requirement as well?

**Comment by rconway** [comment]
Strictly probably yes - but I guess it is a dependency

**Comment by rconway** [comment]
Closed with PR
